### ISSUE TITLE
Video scroll on home page is formatting weirdly 

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/boston-civic-media#8] opened 2016-06-09 14:14 UTC
![screen shot 2016-06-09 at 10 11 53 am](https://cloud.githubusercontent.com/assets/12397944/15932767/e55aaf8e-2e2a-11e6-9adb-fdc6c8401f5f.png)

**Comment by esalling23** [comment] 2016-06-09 14:42
cannot reproduce. closing for now

**Closed by esalling23** 2016-06-09 14:42 UTC
