### ISSUE TITLE
Lightning Talks Page: more space between rows of videos

### ISSUE THREAD

**Issue by kanarinka** [engagementgamelab/boston-civic-media#81] opened 2017-06-02 10:40 UTC
The videos and descriptive text are all bunched together and make it look messy and unclear whether the text that goes with each video is above or below the video. There are also a couple videos that are different aspect ratios and pushing down into the next row. So 2 ways to address:
- Put at least 30-40px between rows of videos to give them space to breathe and make the page less overwhelming. 
- Make sure that different aspect ratios don't push into next row

**Comment by jpailthorpe** [comment] 2017-06-02 14:47
this is a duplicate of #63 , but I'm closing this one because that issue has ore specific information. It is not like this across all screen sizes but instead has to do with how the content is handled in different breakpoints.

**Closed as completed** 2017-06-02 14:52 UTC
